package humanrequest

import "time"

type RequestKind string

const (
	RequestFreeform RequestKind = "freeform"
	RequestApproval RequestKind = "approval"
)

type RequestStatus string

const (
	StatusPending  RequestStatus = "pending"
	StatusResolved RequestStatus = "resolved"
	StatusFailed   RequestStatus = "failed"
)

type ResponderType string

const (
	ResponderCurrentSender ResponderType = "current_sender"
	ResponderOwner         ResponderType = "owner"
)

// ResponderPolicy identifies who may answer a HumanRequest. The model may
// choose Type, but runtime binds the entrypoint and typed sender identity.
type ResponderPolicy struct {
	Type         ResponderType `json:"type,omitempty" yaml:"type,omitempty"`
	EntrypointID string        `json:"entrypoint_id,omitempty" yaml:"entrypoint_id,omitempty"`
	SenderID     string        `json:"sender_id,omitempty" yaml:"sender_id,omitempty"`
	SenderIDType string        `json:"sender_id_type,omitempty" yaml:"sender_id_type,omitempty"`
}

type DeliveryStatus string

const (
	DeliveryNone    DeliveryStatus = "none"
	DeliveryPending DeliveryStatus = "pending"
	DeliverySent    DeliveryStatus = "sent"
	DeliveryFailed  DeliveryStatus = "failed"
)

type DeliveryState struct {
	Status      DeliveryStatus `json:"status,omitempty" yaml:"status,omitempty"`
	MessageID   string         `json:"message_id,omitempty" yaml:"message_id,omitempty"`
	Attempts    int            `json:"attempts,omitempty" yaml:"attempts,omitempty"`
	LastError   string         `json:"last_error,omitempty" yaml:"last_error,omitempty"`
	LastAttempt *time.Time     `json:"last_attempt_at,omitempty" yaml:"last_attempt_at,omitempty"`
	DeliveredAt *time.Time     `json:"delivered_at,omitempty" yaml:"delivered_at,omitempty"`
}

type DeliveryAttempt struct {
	MessageID   string
	Error       string
	AttemptedAt time.Time
}

type ResumeStatus string

const (
	ResumeWaitingResponse ResumeStatus = "waiting_response"
	ResumePending         ResumeStatus = "pending"
	ResumeRunning         ResumeStatus = "running"
	ResumeCompleted       ResumeStatus = "completed"
	ResumeFailed          ResumeStatus = "failed"
)

type ResumeState struct {
	Status      ResumeStatus `json:"status,omitempty" yaml:"status,omitempty"`
	Attempts    int          `json:"attempts,omitempty" yaml:"attempts,omitempty"`
	LastError   string       `json:"last_error,omitempty" yaml:"last_error,omitempty"`
	StartedAt   *time.Time   `json:"started_at,omitempty" yaml:"started_at,omitempty"`
	CompletedAt *time.Time   `json:"completed_at,omitempty" yaml:"completed_at,omitempty"`
}

type ResponseKind string

const (
	ResponseApprove ResponseKind = "approve"
	ResponseDeny    ResponseKind = "deny"
	ResponseCancel  ResponseKind = "cancel"
	ResponseAnswer  ResponseKind = "answer"
)

type HumanOption struct {
	ID    string `json:"id" yaml:"id"`
	Label string `json:"label" yaml:"label"`
}

type HumanRequest struct {
	ID           string          `json:"id" yaml:"id"`
	WorkspaceID  string          `json:"workspace_id" yaml:"workspace_id"`
	WorkspaceKey string          `json:"workspace_key" yaml:"workspace_key"`
	RunID        string          `json:"run_id" yaml:"run_id"`
	AgentID      string          `json:"agent_id" yaml:"agent_id"`
	SessionID    string          `json:"session_id" yaml:"session_id"`
	ToolCallID   string          `json:"tool_call_id,omitempty" yaml:"tool_call_id,omitempty"`
	Source       string          `json:"source,omitempty" yaml:"source,omitempty"`
	Kind         RequestKind     `json:"kind" yaml:"kind"`
	Status       RequestStatus   `json:"status" yaml:"status"`
	Question     string          `json:"question" yaml:"question"`
	Options      []HumanOption   `json:"options,omitempty" yaml:"options,omitempty"`
	DedupeKey    string          `json:"dedupe_key,omitempty" yaml:"dedupe_key,omitempty"`
	Responder    ResponderPolicy `json:"responder,omitempty" yaml:"responder,omitempty"`
	// CorrelationToken is generated by runtime and carried by explicit text or
	// native interaction callbacks. The model never chooses it.
	CorrelationToken string        `json:"correlation_token,omitempty" yaml:"correlation_token,omitempty"`
	Delivery         DeliveryState `json:"delivery,omitempty" yaml:"delivery,omitempty"`
	Resume           ResumeState   `json:"resume,omitempty" yaml:"resume,omitempty"`
	ExpiresAt        *time.Time    `json:"expires_at,omitempty" yaml:"expires_at,omitempty"`
	// ChatKey is the originating chat key (runtime.ChatKey.String(),
	// "channel/chat_id/sender_id") so the Store can answer "which pending HITL
	// belongs to this chat". Stored as string to avoid a humanrequest→runtime
	// import cycle. Empty for requests created before the field existed and for
	// flow_bridge (which has no inbound context yet). #91-A.
	ChatKey    string            `json:"chat_key,omitempty" yaml:"chat_key,omitempty"`
	CreatedAt  time.Time         `json:"created_at" yaml:"created_at"`
	ResolvedAt *time.Time        `json:"resolved_at,omitempty" yaml:"resolved_at,omitempty"`
	Response   *HumanResponse    `json:"response,omitempty" yaml:"response,omitempty"`
	Metadata   map[string]string `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Audit      []AuditRecord     `json:"audit,omitempty" yaml:"audit,omitempty"`
}

type HumanResponse struct {
	ID                string       `json:"id" yaml:"id"`
	RequestID         string       `json:"request_id" yaml:"request_id"`
	Kind              ResponseKind `json:"kind" yaml:"kind"`
	Actor             string       `json:"actor,omitempty" yaml:"actor,omitempty"`
	ActorIDType       string       `json:"actor_id_type,omitempty" yaml:"actor_id_type,omitempty"`
	EntrypointID      string       `json:"entrypoint_id,omitempty" yaml:"entrypoint_id,omitempty"`
	DeliveryMessageID string       `json:"delivery_message_id,omitempty" yaml:"delivery_message_id,omitempty"`
	Message           string       `json:"message,omitempty" yaml:"message,omitempty"`
	IdempotencyKey    string       `json:"idempotency_key,omitempty" yaml:"idempotency_key,omitempty"`
	CreatedAt         time.Time    `json:"created_at" yaml:"created_at"`
}

// HumanResponseEnvelope is the channel-neutral exact response contract. A
// runner authenticates the native event and supplies typed identity; runtime
// and Store revalidate it against the persisted request authority.
type HumanResponseEnvelope struct {
	WorkspaceKey      string
	RequestID         string
	CorrelationToken  string
	EntrypointID      string
	SenderID          string
	SenderIDType      string
	DeliveryMessageID string
	Kind              ResponseKind
	Message           string
	IdempotencyKey    string
	ResolvedAt        time.Time
}

// TextResponseEnvelope is the channel-neutral authority attached to one
// parsed explicit-text response. CorrelationToken comes from the opaque
// protocol reference; all identity and chat fields come from the runner.
type TextResponseEnvelope struct {
	CorrelationToken string
	EntrypointID     string
	SenderID         string
	SenderIDType     string
	ChatKey          string
	ChatType         string
	Answer           string
	IdempotencyKey   string
	ResolvedAt       time.Time
}

type AuditRecord struct {
	Time       time.Time     `json:"time" yaml:"time"`
	Actor      string        `json:"actor,omitempty" yaml:"actor,omitempty"`
	Action     string        `json:"action" yaml:"action"`
	FromStatus RequestStatus `json:"from_status,omitempty" yaml:"from_status,omitempty"`
	ToStatus   RequestStatus `json:"to_status,omitempty" yaml:"to_status,omitempty"`
	Signal     ResponseKind  `json:"signal,omitempty" yaml:"signal,omitempty"`
	Message    string        `json:"message,omitempty" yaml:"message,omitempty"`
}

type CreateRequest struct {
	ID               string
	WorkspaceID      string
	WorkspaceKey     string
	RunID            string
	AgentID          string
	SessionID        string
	ToolCallID       string
	Source           string
	Kind             RequestKind
	Question         string
	Options          []HumanOption
	DedupeKey        string
	Responder        ResponderPolicy
	CorrelationToken string
	DeliveryRequired bool
	ExpiresAt        *time.Time
	// ChatKey is the originating chat key (runtime.ChatKey.String()). Optional —
	// flow_bridge can't fill it yet. #91-A.
	ChatKey   string
	CreatedAt time.Time
	Metadata  map[string]string
}

type ResolveRequest struct {
	WorkspaceKey   string
	RequestID      string
	Kind           ResponseKind
	Actor          string
	Message        string
	IdempotencyKey string
	ResolvedAt     time.Time
}

type ListQuery struct {
	WorkspaceKey string
	Status       RequestStatus
	// ChatKey filters by originating chat (runtime.ChatKey.String()). Empty = no
	// filter (returns all, backward compatible). #91-A.
	ChatKey string
}
